#!/usr/bin/env bash
set -euo pipefail

# REPO BRAIN HOSPITAL - Automatic Documentation Generator (v1.0.0)
# Purpose: Generate docs/SECURITY.md and docs/MODULES.md from detected stack,
#          security findings, and repo classification. Never overwrites existing content.

ROOT="${ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
BRAIN="$ROOT/.repo-brain"
DOCS_DIR="$ROOT/docs"

log() { echo "📄 [docs] $1"; }

JQ="${JQ_BIN:-jq}"

mkdir -p "$DOCS_DIR"

# -------------------------------------------------------
# Load context from prior pipeline phases
# -------------------------------------------------------
framework="unknown"
repo_type="unknown"
languages=""
repo_name="$(basename "$ROOT")"

if [ -f "$BRAIN/detect.json" ]; then
  framework=$("$JQ" -r '.framework // "unknown"' "$BRAIN/detect.json" 2>/dev/null || echo "unknown")
  languages=$("$JQ" -r '[.languages[]?] | join(", ")' "$BRAIN/detect.json" 2>/dev/null || echo "")
fi

if [ -f "$BRAIN/classification.json" ]; then
  repo_type=$("$JQ" -r '.repo_type // "unknown"' "$BRAIN/classification.json" 2>/dev/null || echo "unknown")
fi

# Count security findings from auto-comments
security_finding_count=0
if [ -d "$BRAIN/auto-comments" ]; then
  security_finding_count=$(find "$BRAIN/auto-comments" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
fi

deps_status="No dependency audit data available."
if [ -f "$BRAIN/deps.json" ]; then
  vuln_count=$("$JQ" -r '.findings | length' "$BRAIN/deps.json" 2>/dev/null || echo "0")
  patch_count=$("$JQ" -r '.patched | length' "$BRAIN/deps.json" 2>/dev/null || echo "0")
  deps_status="Audit found $vuln_count finding(s). $patch_count were auto-patched."
fi

# -------------------------------------------------------
# 1. Generate docs/SECURITY.md (skip if already exists)
# -------------------------------------------------------
SECURITY_DOC="$DOCS_DIR/SECURITY.md"
if [ ! -f "$SECURITY_DOC" ]; then
  cat > "$SECURITY_DOC" <<MARKDOWN
# Security Policy

> Auto-generated by REPO BRAIN HOSPITAL on $(date -u +"%Y-%m-%d"). Update this document as your security practices evolve.

## Supported Versions

| Version | Supported |
|---------|-----------|
| latest  | ✅        |

## Reporting a Vulnerability

Please **do not** open a public issue for security vulnerabilities.

1. Email the maintainers at **security@$(echo "$repo_name" | tr '[:upper:]' '[:lower:]').io** (update this address).
2. Include a description of the vulnerability, reproduction steps, and potential impact.
3. We will acknowledge within 48 hours and aim to patch within 14 days.

## Security Scan Summary

- **Last scan**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- **AI Guard findings**: $security_finding_count file(s) flagged
- **Dependency audit**: $deps_status

## Secret Management

All credentials must be stored as encrypted environment variables or in a secret management system (GitHub Secrets, HashiCorp Vault, AWS Secrets Manager). Never hardcode API keys, tokens, or private keys in source code.

## Supported Scanners

This repository is protected by REPO BRAIN HOSPITAL's AI Guard module, which continuously scans for:

- LLM/AI API key exposure (OpenAI, Anthropic, Gemini)
- GitHub token leaks
- AWS/Azure/GCP credential exposure
- Slack and Stripe key leaks
- SSH private key material
- Hardcoded JWT tokens
- Database connection strings with embedded credentials
- Crypto-mining and exfiltration patterns in CI workflows
MARKDOWN
  log "Generated $SECURITY_DOC"
else
  log "SECURITY.md already exists — skipping (no overwrite)."
fi

# -------------------------------------------------------
# 2. Generate docs/MODULES.md (skip if already exists)
# -------------------------------------------------------
MODULES_DOC="$DOCS_DIR/MODULES.md"
if [ ! -f "$MODULES_DOC" ]; then

  # Build module list from shell scripts in BRAIN
  module_table=""
  for script in "$BRAIN"/brain.*.sh; do
    [ -f "$script" ] || continue
    module_name="$(basename "$script")"
    # Extract purpose from the comment on line 4 or 5 (# Purpose: ...)
    purpose=$(grep -m1 "# Purpose:" "$script" 2>/dev/null | sed 's/.*# Purpose: //' || echo "Brain pipeline module")
    module_table="${module_table}| \`$module_name\` | $purpose |\n"
  done

  cat > "$MODULES_DOC" <<MARKDOWN
# Modules Reference

> Auto-generated by REPO BRAIN HOSPITAL on $(date -u +"%Y-%m-%d").

## Repository Profile

| Property | Value |
|----------|-------|
| **Name** | $repo_name |
| **Type** | $repo_type |
| **Framework** | $framework |
| **Languages** | ${languages:-n/a} |

## Brain Pipeline Modules

| Module | Purpose |
|--------|---------|
$(printf '%b' "$module_table")

## Pipeline Execution Order

The modules execute in the following deterministic order via \`brain.run.sh\`:

1. \`brain.detect.sh\` — language & framework detection
2. \`brain.scan-actions.sh\` — CI surface scan, permission hardening, malicious workflow removal
3. \`brain.deps.sh\` — dependency vulnerability audit & patching
4. \`brain.frameworks.sh\` — framework topology
5. \`brain.frameworks.ci.sh\` — CI synthesis
6. \`brain.solidity.detect.sh\` / \`brain.solidity.ci.sh\` — Solidity support
7. \`brain.rust.sh\` — Rust toolchain
8. \`brain.normalize.sh\` — repo normalization & template injection
9. \`brain.vercel.troubleshoot.sh\` — Vercel forensic audit
10. \`brain.diagnose.sh\` — health diagnosis
11. \`brain.fix.safe.sh\` — safe auto-remediation
12. \`brain.verify.sh\` — build/test verification
13. \`brain.ai.guard.sh\` — secret detection & security scan
14. \`brain.classify.sh\` — repository classification
15. \`brain.branch-protect.sh\` — branch protection enforcement
16. \`brain.greenlock.sh\` — governance lock seal
17. \`brain.guard.sh\` — Copilot/LLM behavioral contracts
18. \`brain.docs.sh\` — automatic documentation generation
19. \`brain.fleet.sh\` — fleet telemetry aggregation
MARKDOWN
  log "Generated $MODULES_DOC"
else
  log "MODULES.md already exists — skipping (no overwrite)."
fi

log "Documentation generation complete."
